def n_plus_1 (n) :
    result = n + 1

n_plus_1(3)
print (result)

# result는 정의되지 않았으므로 에러 발생
